

WEBHOOK_URL = "https://a3c669f6ac2e4e77ad43beab3e15be.e7.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/6508b79d8d9d47738297a32e73764c06/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=EZavLDwGHy44ZbU5SarouUBWX7X-iLaBf8JDyxgFSYs"


# tests/send_card_to_teams.py

import json
import requests


from pathlib import Path
import os

# Load the adaptive card generated by the renderer

# Send card to Power Automate


with open(
    "tests/test_renderer_output.json",
    "r",
    encoding="utf-8"
) as f:
    adaptive_card = json.load(f)

response = requests.post(
    WEBHOOK_URL,
    json=adaptive_card
)


print("\nSTATUS:")
print(response.status_code)
