-- 011: the 16-week synthetic inbound arrival schedule, store x SKU.
--
-- `synthetic.inbound_store_sku_16w` is what lets a board draw inbound supply as
-- a calendar instead of a single step. The workbook stores how much is on order
-- per SKU (`open_po_qty`) and never when it lands -- there is no arrival date in
-- any of the 30 tables, which A3's own chart note says outright. With only a
-- lead time to go on, the requirement chart had to place every open PO on its
-- SKU's lead day; the three routes lead 2, 4 and 7 days, so on a weekly chart
-- every one of them arrives inside the first week and cover is flat from W+1
-- onward. Cumulative demand rising against a flat stock diverges without bound,
-- which is why that board read "Cover runs out at W+1" for every scope.
--
-- This table carries 16 forward weeks of arrivals per store x SKU (160 x 800 =
-- 16,000 rows), pivoted wide: one column per week, no dates. Week 1 is the next
-- week ahead -- the same boundary `synthetic.demand_store_sku_32w` encodes with
-- `forecast_w1`, and the two tables are read together.
--
-- IT IS SYNTHETIC, AND SAYS SO. Unlike the demand table it is not calibrated
-- against a workbook cell, because there is no workbook cell to calibrate
-- against; what it is anchored to is the demand curve itself. Total arrivals
-- across the horizon reproduce total forecast demand to within 2% (the
-- generator refuses to write the file otherwise), so cover tracks requirement
-- instead of drifting away from it. `route` is denormalised on purpose: it
-- decides the delivery cadence, and carrying it makes a generated schedule
-- auditable without re-deriving lead times from `dim_item`.
--
-- Generated by scripts/generate_synthetic_inbound_16w.py into
-- resources/inbound_store_sku_16w_v1.csv, and seeded from that CSV by
-- scripts/seed_synthetic_inbound_16w.py. The generator is deterministic -- no
-- seed, no random component -- so the CSV is reproducible from the demand
-- curve and the workbook alone. This migration only creates the shape.
--
-- Rollback: 011_create_synthetic_inbound_16w_rollback.sql

SET XACT_ABORT ON;
GO

IF SCHEMA_ID(N'synthetic') IS NULL
    EXEC('CREATE SCHEMA synthetic;');
GO

IF OBJECT_ID(N'synthetic.inbound_store_sku_16w', N'U') IS NOT NULL
    THROW 50011, 'synthetic.inbound_store_sku_16w already exists; this migration only creates it.', 1;
GO

CREATE TABLE synthetic.inbound_store_sku_16w (
    sku_id      NVARCHAR(30)  NOT NULL,
    store_id    NVARCHAR(20)  NOT NULL,
    route       NVARCHAR(20)  NOT NULL,
    arrival_w1  DECIMAL(20,6) NOT NULL,
    arrival_w2  DECIMAL(20,6) NOT NULL,
    arrival_w3  DECIMAL(20,6) NOT NULL,
    arrival_w4  DECIMAL(20,6) NOT NULL,
    arrival_w5  DECIMAL(20,6) NOT NULL,
    arrival_w6  DECIMAL(20,6) NOT NULL,
    arrival_w7  DECIMAL(20,6) NOT NULL,
    arrival_w8  DECIMAL(20,6) NOT NULL,
    arrival_w9  DECIMAL(20,6) NOT NULL,
    arrival_w10 DECIMAL(20,6) NOT NULL,
    arrival_w11 DECIMAL(20,6) NOT NULL,
    arrival_w12 DECIMAL(20,6) NOT NULL,
    arrival_w13 DECIMAL(20,6) NOT NULL,
    arrival_w14 DECIMAL(20,6) NOT NULL,
    arrival_w15 DECIMAL(20,6) NOT NULL,
    arrival_w16 DECIMAL(20,6) NOT NULL,
    CONSTRAINT PK_synthetic_inbound_store_sku_16w PRIMARY KEY (sku_id, store_id)
);
GO
