-- 012: 16-week forward projection of markdown at-risk exposure, store x SKU.
--
-- `synthetic.markdown_ladder_store_sku_16w` is what lets A5's "at-risk value:
-- ladder vs no action" chart draw a weekly line. Unlike demand, at-risk value
-- has no real PAST to record -- it is a snapshot metric read off today's
-- inventory position, not a rate with history to backtest -- so this is not a
-- history table and does not pretend to be one. It is a deterministic FORWARD
-- projection, 16 weeks out, of today's real at-risk exposure under two
-- policies: do nothing (`no_action_w*`), or keep running the markdown ladder
-- (`ladder_w*`). Week 1 of both is pinned exactly to today's real
-- at_risk_value/write_off_value (f12/f14) -- nothing about week 1 is
-- invented, only the 15 weeks ahead of it.
--
-- This table carries 16 forward weeks per store x SKU (160 x 800 = 16,000
-- rows), pivoted wide: one column per week, no dates. Same shape as
-- `synthetic.inbound_store_sku_16w`, and read the same way.
--
-- IT IS SYNTHETIC, AND SAYS SO. Weeks 2-16 of both lines are a function of
-- each row's own real at_risk_value/write_off_value/growth/state -- never a
-- random draw -- gated at generation time (calibration, monotonic no-action,
-- ladder/no-action separation, and a per-vertical separation floor) before
-- being written. See scripts/generate_synthetic_markdown_ladder_16w.py's
-- module docstring for the exact assumptions and why each one was chosen.
--
-- Generated by scripts/generate_synthetic_markdown_ladder_16w.py into
-- resources/markdown_ladder_store_sku_16w_v1.csv, and seeded from that CSV by
-- scripts/seed_synthetic_markdown_ladder_16w.py. The generator is
-- deterministic -- no seed, no random component -- so the CSV is reproducible
-- from today's fixture inputs alone. This migration only creates the shape.
--
-- Purely additive: does not touch, alter, or rename any existing table
-- (`synthetic.demand_store_sku_32w`, `synthetic.inbound_store_sku_16w`,
-- `retail.dim_item`, `retail.fact_inventory_daily`, etc. are all untouched).
--
-- Rollback: 012_create_synthetic_markdown_ladder_16w_rollback.sql

SET XACT_ABORT ON;
GO

IF SCHEMA_ID(N'synthetic') IS NULL
    EXEC('CREATE SCHEMA synthetic;');
GO

IF OBJECT_ID(N'synthetic.markdown_ladder_store_sku_16w', N'U') IS NOT NULL
    THROW 50012, 'synthetic.markdown_ladder_store_sku_16w already exists; this migration only creates it.', 1;
GO

CREATE TABLE synthetic.markdown_ladder_store_sku_16w (
    sku_id         NVARCHAR(30)  NOT NULL,
    store_id       NVARCHAR(20)  NOT NULL,
    no_action_w1   DECIMAL(20,6) NOT NULL,
    no_action_w2   DECIMAL(20,6) NOT NULL,
    no_action_w3   DECIMAL(20,6) NOT NULL,
    no_action_w4   DECIMAL(20,6) NOT NULL,
    no_action_w5   DECIMAL(20,6) NOT NULL,
    no_action_w6   DECIMAL(20,6) NOT NULL,
    no_action_w7   DECIMAL(20,6) NOT NULL,
    no_action_w8   DECIMAL(20,6) NOT NULL,
    no_action_w9   DECIMAL(20,6) NOT NULL,
    no_action_w10  DECIMAL(20,6) NOT NULL,
    no_action_w11  DECIMAL(20,6) NOT NULL,
    no_action_w12  DECIMAL(20,6) NOT NULL,
    no_action_w13  DECIMAL(20,6) NOT NULL,
    no_action_w14  DECIMAL(20,6) NOT NULL,
    no_action_w15  DECIMAL(20,6) NOT NULL,
    no_action_w16  DECIMAL(20,6) NOT NULL,
    ladder_w1      DECIMAL(20,6) NOT NULL,
    ladder_w2      DECIMAL(20,6) NOT NULL,
    ladder_w3      DECIMAL(20,6) NOT NULL,
    ladder_w4      DECIMAL(20,6) NOT NULL,
    ladder_w5      DECIMAL(20,6) NOT NULL,
    ladder_w6      DECIMAL(20,6) NOT NULL,
    ladder_w7      DECIMAL(20,6) NOT NULL,
    ladder_w8      DECIMAL(20,6) NOT NULL,
    ladder_w9      DECIMAL(20,6) NOT NULL,
    ladder_w10     DECIMAL(20,6) NOT NULL,
    ladder_w11     DECIMAL(20,6) NOT NULL,
    ladder_w12     DECIMAL(20,6) NOT NULL,
    ladder_w13     DECIMAL(20,6) NOT NULL,
    ladder_w14     DECIMAL(20,6) NOT NULL,
    ladder_w15     DECIMAL(20,6) NOT NULL,
    ladder_w16     DECIMAL(20,6) NOT NULL,
    CONSTRAINT PK_synthetic_markdown_ladder_store_sku_16w PRIMARY KEY (sku_id, store_id),
    CONSTRAINT CK_synthetic_markdown_ladder_store_sku_16w_non_negative CHECK (
        no_action_w1 >= 0 AND no_action_w2 >= 0 AND no_action_w3 >= 0 AND no_action_w4 >= 0 AND
        no_action_w5 >= 0 AND no_action_w6 >= 0 AND no_action_w7 >= 0 AND no_action_w8 >= 0 AND
        no_action_w9 >= 0 AND no_action_w10 >= 0 AND no_action_w11 >= 0 AND no_action_w12 >= 0 AND
        no_action_w13 >= 0 AND no_action_w14 >= 0 AND no_action_w15 >= 0 AND no_action_w16 >= 0 AND
        ladder_w1 >= 0 AND ladder_w2 >= 0 AND ladder_w3 >= 0 AND ladder_w4 >= 0 AND
        ladder_w5 >= 0 AND ladder_w6 >= 0 AND ladder_w7 >= 0 AND ladder_w8 >= 0 AND
        ladder_w9 >= 0 AND ladder_w10 >= 0 AND ladder_w11 >= 0 AND ladder_w12 >= 0 AND
        ladder_w13 >= 0 AND ladder_w14 >= 0 AND ladder_w15 >= 0 AND ladder_w16 >= 0
    )
);
GO
